[phases.setup]
aptPkgs = [
    "python3-distutils",
    "python3-setuptools", 
    "python3-dev",
    "default-libmysqlclient-dev",
    "pkg-config",
    "build-essential",
    "python3-pip"
]

[phases.build]
cmds = [
    "apt-get update",
    "apt-get install -y python3-distutils",
    "python -m venv --copies --without-pip /opt/venv",
    ". /opt/venv/bin/activate && python -m ensurepip --upgrade",
    ". /opt/venv/bin/activate && pip install --no-cache-dir --upgrade pip setuptools wheel",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]
