[phases.setup]
aptPkgs = [
    "python3-distutils",
    "python3-setuptools", 
    "python3-dev",
    "default-libmysqlclient-dev",
    "pkg-config",
    "build-essential"
]

[phases.build]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip setuptools",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]
