[build]
builder = "nixpacks"
buildCommand = "pip install --only-binary :all: -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
aptPkgs = [
    "python3-distutils",
    "python3-setuptools",
    "python3-dev",
    "default-libmysqlclient-dev",
    "pkg-config",
    "build-essential",
    "libpq-dev",
    "python3-numpy"
]
